# Generated by Django 2.1 on 2019-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
