# Generated by Django 2.1 on 2019-02-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190225_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
