# Generated by Django 2.1 on 2019-02-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190226_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsleft',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='ticketsleft',
            name='tickets',
        ),
        migrations.DeleteModel(
            name='TicketsLeft',
        ),
    ]
